- include: pacman.yml
- include: network.yml
- include: core.yml
- include: config.yml
- include: yubikey.yml
- include: shell.yml
- include: audio.yml
- include: bluetooth.yml
- include: video-player.yml
- include: image-viewer.yml
- include: pdf-reader.yml
- include: editor.yml
- include: fonts.yml
- include: playerctl.yml
- include: printer.yml

